server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://122.9.45.57:3306/hxt?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: hxt
    password: ruangong-0602-g1
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.hxt.backend.entity